packages:
  - .
  - examples/*
  - playground

catalog:
  '@tanstack/react-query': 5.90.5
  '@types/react': ^19.1.16
  '@types/react-dom': ^19.1.9
  '@vitejs/plugin-react': ^5.0.4
  '@wagmi/core': ^2.22.1
  prool: 0.0.25
  react: ^19.1.1
  react-dom: ^19.1.1
  typescript: ^5.9.3
  viem: https://pkg.pr.new/viem@main
  wagmi: 3.0.1

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
