// Generated with `bun run gen:abis`. Do not modify manually.

export const tip20 = [
  {
    name: 'name',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'string' }],
  },
  {
    name: 'symbol',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'string' }],
  },
  {
    name: 'decimals',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint8' }],
  },
  {
    name: 'totalSupply',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    name: 'linkingToken',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'address' }],
  },
  {
    name: 'nextLinkingToken',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'address' }],
  },
  {
    name: 'balanceOf',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ type: 'address', name: 'account' }],
    outputs: [{ type: 'uint256' }],
  },
  {
    name: 'transfer',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { type: 'address', name: 'to' },
      { type: 'uint256', name: 'amount' },
    ],
    outputs: [{ type: 'bool' }],
  },
  {
    name: 'approve',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { type: 'address', name: 'spender' },
      { type: 'uint256', name: 'amount' },
    ],
    outputs: [{ type: 'bool' }],
  },
  {
    name: 'allowance',
    type: 'function',
    stateMutability: 'view',
    inputs: [
      { type: 'address', name: 'owner' },
      { type: 'address', name: 'spender' },
    ],
    outputs: [{ type: 'uint256' }],
  },
  {
    name: 'transferFrom',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { type: 'address', name: 'from' },
      { type: 'address', name: 'to' },
      { type: 'uint256', name: 'amount' },
    ],
    outputs: [{ type: 'bool' }],
  },
  {
    name: 'mint',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { type: 'address', name: 'to' },
      { type: 'uint256', name: 'amount' },
    ],
    outputs: [],
  },
  {
    name: 'burn',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{ type: 'uint256', name: 'amount' }],
    outputs: [],
  },
  {
    name: 'currency',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'string' }],
  },
  {
    name: 'supplyCap',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    name: 'paused',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'bool' }],
  },
  {
    name: 'transferPolicyId',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint64' }],
  },
  {
    name: 'nonces',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ type: 'address', name: 'owner' }],
    outputs: [{ type: 'uint256' }],
  },
  {
    name: 'salts',
    type: 'function',
    stateMutability: 'view',
    inputs: [
      { type: 'address', name: 'owner' },
      { type: 'bytes4', name: 'salt' },
    ],
    outputs: [{ type: 'bool' }],
  },
  {
    name: 'burnBlocked',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { type: 'address', name: 'from' },
      { type: 'uint256', name: 'amount' },
    ],
    outputs: [],
  },
  {
    name: 'mintWithMemo',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { type: 'address', name: 'to' },
      { type: 'uint256', name: 'amount' },
      { type: 'bytes32', name: 'memo' },
    ],
    outputs: [],
  },
  {
    name: 'burnWithMemo',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { type: 'uint256', name: 'amount' },
      { type: 'bytes32', name: 'memo' },
    ],
    outputs: [],
  },
  {
    name: 'transferWithMemo',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { type: 'address', name: 'to' },
      { type: 'uint256', name: 'amount' },
      { type: 'bytes32', name: 'memo' },
    ],
    outputs: [],
  },
  {
    name: 'transferFromWithMemo',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { type: 'address', name: 'from' },
      { type: 'address', name: 'to' },
      { type: 'uint256', name: 'amount' },
      { type: 'bytes32', name: 'memo' },
    ],
    outputs: [{ type: 'bool' }],
  },
  {
    name: 'changeTransferPolicyId',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{ type: 'uint64', name: 'newPolicyId' }],
    outputs: [],
  },
  {
    name: 'setSupplyCap',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{ type: 'uint256', name: 'newSupplyCap' }],
    outputs: [],
  },
  {
    name: 'pause',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    name: 'unpause',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    name: 'updateLinkingToken',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{ type: 'address', name: 'newLinkingToken' }],
    outputs: [],
  },
  {
    name: 'finalizeLinkingTokenUpdate',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    name: 'permit',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { type: 'address', name: 'owner' },
      { type: 'address', name: 'spender' },
      { type: 'uint256', name: 'value' },
      { type: 'uint256', name: 'deadline' },
      { type: 'uint8', name: 'v' },
      { type: 'bytes32', name: 'r' },
      { type: 'bytes32', name: 's' },
    ],
    outputs: [],
  },
  {
    name: 'DOMAIN_SEPARATOR',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'bytes32' }],
  },
  {
    name: 'Transfer',
    type: 'event',
    inputs: [
      { type: 'address', name: 'from', indexed: true },
      { type: 'address', name: 'to', indexed: true },
      { type: 'uint256', name: 'amount' },
    ],
  },
  {
    name: 'Approval',
    type: 'event',
    inputs: [
      { type: 'address', name: 'owner', indexed: true },
      { type: 'address', name: 'spender', indexed: true },
      { type: 'uint256', name: 'amount' },
    ],
  },
  {
    name: 'Mint',
    type: 'event',
    inputs: [
      { type: 'address', name: 'to', indexed: true },
      { type: 'uint256', name: 'amount' },
    ],
  },
  {
    name: 'Burn',
    type: 'event',
    inputs: [
      { type: 'address', name: 'from', indexed: true },
      { type: 'uint256', name: 'amount' },
    ],
  },
  {
    name: 'BurnBlocked',
    type: 'event',
    inputs: [
      { type: 'address', name: 'from', indexed: true },
      { type: 'uint256', name: 'amount' },
    ],
  },
  {
    name: 'TransferWithMemo',
    type: 'event',
    inputs: [
      { type: 'address', name: 'from', indexed: true },
      { type: 'address', name: 'to', indexed: true },
      { type: 'uint256', name: 'amount' },
      { type: 'bytes32', name: 'memo' },
    ],
  },
  {
    name: 'TransferPolicyUpdate',
    type: 'event',
    inputs: [
      { type: 'address', name: 'updater', indexed: true },
      { type: 'uint64', name: 'newPolicyId', indexed: true },
    ],
  },
  {
    name: 'SupplyCapUpdate',
    type: 'event',
    inputs: [
      { type: 'address', name: 'updater', indexed: true },
      { type: 'uint256', name: 'newSupplyCap', indexed: true },
    ],
  },
  {
    name: 'PauseStateUpdate',
    type: 'event',
    inputs: [
      { type: 'address', name: 'updater', indexed: true },
      { type: 'bool', name: 'isPaused' },
    ],
  },
  {
    name: 'UpdateLinkingToken',
    type: 'event',
    inputs: [
      { type: 'address', name: 'updater', indexed: true },
      { type: 'address', name: 'newLinkingToken', indexed: true },
    ],
  },
  {
    name: 'LinkingTokenUpdateFinalized',
    type: 'event',
    inputs: [
      { type: 'address', name: 'updater', indexed: true },
      { type: 'address', name: 'newLinkingToken', indexed: true },
    ],
  },
  { name: 'InsufficientBalance', type: 'error', inputs: [] },
  { name: 'InsufficientAllowance', type: 'error', inputs: [] },
  { name: 'SupplyCapExceeded', type: 'error', inputs: [] },
  { name: 'InvalidSignature', type: 'error', inputs: [] },
  { name: 'InvalidPayload', type: 'error', inputs: [] },
  { name: 'InvalidNonce', type: 'error', inputs: [] },
  { name: 'StringTooLong', type: 'error', inputs: [] },
  { name: 'PolicyForbids', type: 'error', inputs: [] },
  { name: 'InvalidRecipient', type: 'error', inputs: [] },
  { name: 'Expired', type: 'error', inputs: [] },
  { name: 'SaltAlreadyUsed', type: 'error', inputs: [] },
  { name: 'ContractPaused', type: 'error', inputs: [] },
  { name: 'InvalidCurrency', type: 'error', inputs: [] },
  { name: 'InvalidLinkingToken', type: 'error', inputs: [] },
  { name: 'TransfersDisabled', type: 'error', inputs: [] },
  {
    name: 'grantRole',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { type: 'bytes32', name: 'role' },
      { type: 'address', name: 'account' },
    ],
    outputs: [],
  },
  {
    name: 'revokeRole',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { type: 'bytes32', name: 'role' },
      { type: 'address', name: 'account' },
    ],
    outputs: [],
  },
  {
    name: 'renounceRole',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{ type: 'bytes32', name: 'role' }],
    outputs: [],
  },
  {
    name: 'setRoleAdmin',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { type: 'bytes32', name: 'role' },
      { type: 'bytes32', name: 'adminRole' },
    ],
    outputs: [],
  },
  {
    name: 'hasRole',
    type: 'function',
    stateMutability: 'view',
    inputs: [
      { type: 'address', name: 'account' },
      { type: 'bytes32', name: 'role' },
    ],
    outputs: [{ type: 'bool' }],
  },
  {
    name: 'getRoleAdmin',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ type: 'bytes32', name: 'role' }],
    outputs: [{ type: 'bytes32' }],
  },
  {
    name: 'RoleMembershipUpdated',
    type: 'event',
    inputs: [
      { type: 'bytes32', name: 'role', indexed: true },
      { type: 'address', name: 'account', indexed: true },
      { type: 'address', name: 'sender', indexed: true },
      { type: 'bool', name: 'hasRole' },
    ],
  },
  {
    name: 'RoleAdminUpdated',
    type: 'event',
    inputs: [
      { type: 'bytes32', name: 'role', indexed: true },
      { type: 'bytes32', name: 'newAdminRole', indexed: true },
      { type: 'address', name: 'sender', indexed: true },
    ],
  },
  { name: 'Unauthorized', type: 'error', inputs: [] },
] as const

export const tip20Factory = [
  {
    name: 'createToken',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { type: 'string', name: 'name' },
      { type: 'string', name: 'symbol' },
      { type: 'string', name: 'currency' },
      { type: 'address', name: 'linkingToken' },
      { type: 'address', name: 'admin' },
    ],
    outputs: [{ type: 'uint256' }],
  },
  {
    name: 'tokenIdCounter',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    name: 'TokenCreated',
    type: 'event',
    inputs: [
      { type: 'address', name: 'token', indexed: true },
      { type: 'uint256', name: 'tokenId', indexed: true },
      { type: 'string', name: 'name' },
      { type: 'string', name: 'symbol' },
      { type: 'string', name: 'currency' },
      { type: 'address', name: 'admin' },
    ],
  },
] as const

export const tip403Registry = [
  {
    name: 'policyIdCounter',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint64' }],
  },
  {
    name: 'policyData',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ type: 'uint64', name: 'policyId' }],
    outputs: [
      { type: 'uint8', name: 'policyType' },
      { type: 'address', name: 'admin' },
    ],
  },
  {
    name: 'isAuthorized',
    type: 'function',
    stateMutability: 'view',
    inputs: [
      { type: 'uint64', name: 'policyId' },
      { type: 'address', name: 'user' },
    ],
    outputs: [{ type: 'bool' }],
  },
  {
    name: 'createPolicy',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { type: 'address', name: 'admin' },
      { type: 'uint8', name: 'policyType' },
    ],
    outputs: [{ type: 'uint64' }],
  },
  {
    name: 'createPolicyWithAccounts',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { type: 'address', name: 'admin' },
      { type: 'uint8', name: 'policyType' },
      { type: 'address[]', name: 'accounts' },
    ],
    outputs: [{ type: 'uint64' }],
  },
  {
    name: 'setPolicyAdmin',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { type: 'uint64', name: 'policyId' },
      { type: 'address', name: 'admin' },
    ],
    outputs: [],
  },
  {
    name: 'modifyPolicyWhitelist',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { type: 'uint64', name: 'policyId' },
      { type: 'address', name: 'account' },
      { type: 'bool', name: 'allowed' },
    ],
    outputs: [],
  },
  {
    name: 'modifyPolicyBlacklist',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { type: 'uint64', name: 'policyId' },
      { type: 'address', name: 'account' },
      { type: 'bool', name: 'restricted' },
    ],
    outputs: [],
  },
  {
    name: 'PolicyAdminUpdated',
    type: 'event',
    inputs: [
      { type: 'uint64', name: 'policyId', indexed: true },
      { type: 'address', name: 'updater', indexed: true },
      { type: 'address', name: 'admin', indexed: true },
    ],
  },
  {
    name: 'PolicyCreated',
    type: 'event',
    inputs: [
      { type: 'uint64', name: 'policyId', indexed: true },
      { type: 'address', name: 'updater', indexed: true },
      { type: 'uint8', name: 'policyType' },
    ],
  },
  {
    name: 'WhitelistUpdated',
    type: 'event',
    inputs: [
      { type: 'uint64', name: 'policyId', indexed: true },
      { type: 'address', name: 'updater', indexed: true },
      { type: 'address', name: 'account', indexed: true },
      { type: 'bool', name: 'allowed' },
    ],
  },
  {
    name: 'BlacklistUpdated',
    type: 'event',
    inputs: [
      { type: 'uint64', name: 'policyId', indexed: true },
      { type: 'address', name: 'updater', indexed: true },
      { type: 'address', name: 'account', indexed: true },
      { type: 'bool', name: 'restricted' },
    ],
  },
  { name: 'Unauthorized', type: 'error', inputs: [] },
  { name: 'IncompatiblePolicyType', type: 'error', inputs: [] },
  { name: 'SelfOwnedPolicyMustBeWhitelist', type: 'error', inputs: [] },
] as const

export const tip4217Registry = [
  {
    name: 'getCurrencyDecimals',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ type: 'string', name: 'currency' }],
    outputs: [{ type: 'uint8' }],
  },
] as const

export const tipAccountRegistrar = [
  {
    name: 'delegateToDefault',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { type: 'bytes32', name: 'hash' },
      { type: 'bytes', name: 'signature' },
    ],
    outputs: [{ type: 'address', name: 'authority' }],
  },
  {
    name: 'getDelegationMessage',
    type: 'function',
    stateMutability: 'pure',
    inputs: [],
    outputs: [{ type: 'string' }],
  },
  { name: 'InvalidSignature', type: 'error', inputs: [] },
  { name: 'CodeNotEmpty', type: 'error', inputs: [] },
  { name: 'NonceNotZero', type: 'error', inputs: [] },
] as const

export const feeAmm = [
  {
    name: 'getPoolId',
    type: 'function',
    stateMutability: 'pure',
    inputs: [
      { type: 'address', name: 'userToken' },
      { type: 'address', name: 'validatorToken' },
    ],
    outputs: [{ type: 'bytes32' }],
  },
  {
    name: 'getPool',
    type: 'function',
    stateMutability: 'view',
    inputs: [
      { type: 'address', name: 'userToken' },
      { type: 'address', name: 'validatorToken' },
    ],
    outputs: [
      {
        type: 'tuple',
        components: [
          { type: 'uint128', name: 'reserveUserToken' },
          { type: 'uint128', name: 'reserveValidatorToken' },
        ],
      },
    ],
  },
  {
    name: 'pools',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ type: 'bytes32', name: 'poolId' }],
    outputs: [
      {
        type: 'tuple',
        components: [
          { type: 'uint128', name: 'reserveUserToken' },
          { type: 'uint128', name: 'reserveValidatorToken' },
        ],
      },
    ],
  },
  {
    name: 'mint',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { type: 'address', name: 'userToken' },
      { type: 'address', name: 'validatorToken' },
      { type: 'uint256', name: 'amountUserToken' },
      { type: 'uint256', name: 'amountValidatorToken' },
      { type: 'address', name: 'to' },
    ],
    outputs: [{ type: 'uint256', name: 'liquidity' }],
  },
  {
    name: 'burn',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { type: 'address', name: 'userToken' },
      { type: 'address', name: 'validatorToken' },
      { type: 'uint256', name: 'liquidity' },
      { type: 'address', name: 'to' },
    ],
    outputs: [
      { type: 'uint256', name: 'amountUserToken' },
      { type: 'uint256', name: 'amountValidatorToken' },
    ],
  },
  {
    name: 'totalSupply',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ type: 'bytes32', name: 'poolId' }],
    outputs: [{ type: 'uint256' }],
  },
  {
    name: 'liquidityBalances',
    type: 'function',
    stateMutability: 'view',
    inputs: [
      { type: 'bytes32', name: 'poolId' },
      { type: 'address', name: 'user' },
    ],
    outputs: [{ type: 'uint256' }],
  },
  {
    name: 'rebalanceSwap',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { type: 'address', name: 'userToken' },
      { type: 'address', name: 'validatorToken' },
      { type: 'uint256', name: 'amountOut' },
      { type: 'address', name: 'to' },
    ],
    outputs: [{ type: 'uint256', name: 'amountIn' }],
  },
  {
    name: 'calculateLiquidity',
    type: 'function',
    stateMutability: 'pure',
    inputs: [
      { type: 'uint256', name: 'x' },
      { type: 'uint256', name: 'y' },
    ],
    outputs: [{ type: 'uint256' }],
  },
  {
    name: 'Mint',
    type: 'event',
    inputs: [
      { type: 'address', name: 'sender', indexed: true },
      { type: 'address', name: 'userToken', indexed: true },
      { type: 'address', name: 'validatorToken', indexed: true },
      { type: 'uint256', name: 'amountUserToken' },
      { type: 'uint256', name: 'amountValidatorToken' },
      { type: 'uint256', name: 'liquidity' },
    ],
  },
  {
    name: 'Burn',
    type: 'event',
    inputs: [
      { type: 'address', name: 'sender', indexed: true },
      { type: 'address', name: 'userToken', indexed: true },
      { type: 'address', name: 'validatorToken', indexed: true },
      { type: 'uint256', name: 'amountUserToken' },
      { type: 'uint256', name: 'amountValidatorToken' },
      { type: 'uint256', name: 'liquidity' },
      { type: 'address', name: 'to' },
    ],
  },
  {
    name: 'RebalanceSwap',
    type: 'event',
    inputs: [
      { type: 'address', name: 'userToken', indexed: true },
      { type: 'address', name: 'validatorToken', indexed: true },
      { type: 'address', name: 'swapper', indexed: true },
      { type: 'uint256', name: 'amountIn' },
      { type: 'uint256', name: 'amountOut' },
    ],
  },
  {
    name: 'FeeSwap',
    type: 'event',
    inputs: [
      { type: 'address', name: 'userToken', indexed: true },
      { type: 'address', name: 'validatorToken', indexed: true },
      { type: 'uint256', name: 'amountIn' },
      { type: 'uint256', name: 'amountOut' },
    ],
  },
  { name: 'IdenticalAddresses', type: 'error', inputs: [] },
  { name: 'ZeroAddress', type: 'error', inputs: [] },
  { name: 'PoolExists', type: 'error', inputs: [] },
  { name: 'PoolDoesNotExist', type: 'error', inputs: [] },
  { name: 'InvalidToken', type: 'error', inputs: [] },
  { name: 'InsufficientLiquidity', type: 'error', inputs: [] },
  { name: 'OnlyProtocol', type: 'error', inputs: [] },
  { name: 'InsufficientPoolBalance', type: 'error', inputs: [] },
  { name: 'InsufficientReserves', type: 'error', inputs: [] },
  { name: 'InsufficientLiquidityBalance', type: 'error', inputs: [] },
  { name: 'MustDepositLowerBalanceToken', type: 'error', inputs: [] },
  { name: 'InvalidAmount', type: 'error', inputs: [] },
  { name: 'InvalidRebalanceState', type: 'error', inputs: [] },
  { name: 'InvalidRebalanceDirection', type: 'error', inputs: [] },
  { name: 'InvalidNewReserves', type: 'error', inputs: [] },
  { name: 'CannotSupportPendingSwaps', type: 'error', inputs: [] },
  { name: 'DivisionByZero', type: 'error', inputs: [] },
  { name: 'InvalidSwapCalculation', type: 'error', inputs: [] },
  { name: 'InsufficientLiquidityForPending', type: 'error', inputs: [] },
  { name: 'TokenTransferFailed', type: 'error', inputs: [] },
  { name: 'InternalError', type: 'error', inputs: [] },
] as const

export const feeManager = [
  {
    name: 'BASIS_POINTS',
    type: 'function',
    stateMutability: 'pure',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    name: 'FEE_BPS',
    type: 'function',
    stateMutability: 'pure',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    name: 'userTokens',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ type: 'address', name: 'user' }],
    outputs: [{ type: 'address' }],
  },
  {
    name: 'validatorTokens',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ type: 'address', name: 'validator' }],
    outputs: [{ type: 'address' }],
  },
  {
    name: 'setUserToken',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{ type: 'address', name: 'token' }],
    outputs: [],
  },
  {
    name: 'setValidatorToken',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{ type: 'address', name: 'token' }],
    outputs: [],
  },
  {
    name: 'getFeeTokenBalance',
    type: 'function',
    stateMutability: 'view',
    inputs: [
      { type: 'address', name: 'sender' },
      { type: 'address', name: 'validator' },
    ],
    outputs: [{ type: 'address' }, { type: 'uint256' }],
  },
  {
    name: 'executeBlock',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    name: 'UserTokenSet',
    type: 'event',
    inputs: [
      { type: 'address', name: 'user', indexed: true },
      { type: 'address', name: 'token', indexed: true },
    ],
  },
  {
    name: 'ValidatorTokenSet',
    type: 'event',
    inputs: [
      { type: 'address', name: 'validator', indexed: true },
      { type: 'address', name: 'token', indexed: true },
    ],
  },
  { name: 'OnlyValidator', type: 'error', inputs: [] },
  { name: 'OnlySystemContract', type: 'error', inputs: [] },
  { name: 'InvalidToken', type: 'error', inputs: [] },
  { name: 'PoolDoesNotExist', type: 'error', inputs: [] },
  { name: 'InsufficientLiquidity', type: 'error', inputs: [] },
  { name: 'InsufficientFeeTokenBalance', type: 'error', inputs: [] },
  { name: 'InternalError', type: 'error', inputs: [] },
  { name: 'CannotChangeWithinBlock', type: 'error', inputs: [] },
  { name: 'TokenPolicyForbids', type: 'error', inputs: [] },
] as const

export const stablecoinDex = [
  {
    name: 'balanceOf',
    type: 'function',
    stateMutability: 'view',
    inputs: [
      { type: 'address', name: 'user' },
      { type: 'address', name: 'token' },
    ],
    outputs: [{ type: 'uint128' }],
  },
  {
    name: 'quoteBuy',
    type: 'function',
    stateMutability: 'view',
    inputs: [
      { type: 'address', name: 'tokenIn' },
      { type: 'address', name: 'tokenOut' },
      { type: 'uint128', name: 'amountOut' },
    ],
    outputs: [{ type: 'uint128', name: 'amountIn' }],
  },
  {
    name: 'quoteSell',
    type: 'function',
    stateMutability: 'view',
    inputs: [
      { type: 'address', name: 'tokenIn' },
      { type: 'address', name: 'tokenOut' },
      { type: 'uint128', name: 'amountIn' },
    ],
    outputs: [{ type: 'uint128', name: 'amountOut' }],
  },
  {
    name: 'sell',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { type: 'address', name: 'tokenIn' },
      { type: 'address', name: 'tokenOut' },
      { type: 'uint128', name: 'amountIn' },
      { type: 'uint128', name: 'minAmountOut' },
    ],
    outputs: [{ type: 'uint128', name: 'amountOut' }],
  },
  {
    name: 'buy',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { type: 'address', name: 'tokenIn' },
      { type: 'address', name: 'tokenOut' },
      { type: 'uint128', name: 'amountOut' },
      { type: 'uint128', name: 'maxAmountIn' },
    ],
    outputs: [{ type: 'uint128', name: 'amountIn' }],
  },
  {
    name: 'place',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { type: 'address', name: 'token' },
      { type: 'uint128', name: 'amount' },
      { type: 'bool', name: 'isBid' },
      { type: 'int16', name: 'tick' },
    ],
    outputs: [{ type: 'uint128', name: 'orderId' }],
  },
  {
    name: 'placeFlip',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { type: 'address', name: 'token' },
      { type: 'uint128', name: 'amount' },
      { type: 'bool', name: 'isBid' },
      { type: 'int16', name: 'tick' },
      { type: 'int16', name: 'flipTick' },
    ],
    outputs: [{ type: 'uint128', name: 'orderId' }],
  },
  {
    name: 'cancel',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{ type: 'uint128', name: 'orderId' }],
    outputs: [],
  },
  {
    name: 'withdraw',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { type: 'address', name: 'token' },
      { type: 'uint128', name: 'amount' },
    ],
    outputs: [],
  },
  {
    name: 'OrderPlaced',
    type: 'event',
    inputs: [
      { type: 'uint128', name: 'orderId', indexed: true },
      { type: 'address', name: 'maker', indexed: true },
      { type: 'address', name: 'token', indexed: true },
      { type: 'uint128', name: 'amount' },
      { type: 'bool', name: 'isBid' },
      { type: 'int16', name: 'tick' },
    ],
  },
  {
    name: 'FlipOrderPlaced',
    type: 'event',
    inputs: [
      { type: 'uint128', name: 'orderId', indexed: true },
      { type: 'address', name: 'maker', indexed: true },
      { type: 'address', name: 'token', indexed: true },
      { type: 'uint128', name: 'amount' },
      { type: 'bool', name: 'isBid' },
      { type: 'int16', name: 'tick' },
      { type: 'int16', name: 'flipTick' },
    ],
  },
  {
    name: 'OrderCancelled',
    type: 'event',
    inputs: [{ type: 'uint128', name: 'orderId', indexed: true }],
  },
  {
    name: 'OrderFilled',
    type: 'event',
    inputs: [
      { type: 'uint128', name: 'orderId', indexed: true },
      { type: 'address', name: 'maker', indexed: true },
      { type: 'address', name: 'taker', indexed: true },
      { type: 'uint128', name: 'amountFilled' },
      { type: 'bool', name: 'partialFill' },
    ],
  },
  { name: 'OrderDoesNotExist', type: 'error', inputs: [] },
  { name: 'Unauthorized', type: 'error', inputs: [] },
  { name: 'InsufficientBalance', type: 'error', inputs: [] },
  { name: 'InvalidFlipTick', type: 'error', inputs: [] },
] as const
