// Generated with `bun run gen:abis`. Do not modify manually.

import * as Abi from 'ox/Abi'

export const tip20Abi = Abi.from([
  'struct Permit { address owner; address spender; uint256 value; uint256 nonce; uint256 deadline; }',
  'function name() external view returns (string)',
  'function symbol() external view returns (string)',
  'function decimals() external view returns (uint8)',
  'function totalSupply() external view returns (uint256)',
  'function linkingToken() external view returns (address)',
  'function nextLinkingToken() external view returns (address)',
  'function balanceOf(address account) external view returns (uint256)',
  'function transfer(address to, uint256 amount) external returns (bool)',
  'function approve(address spender, uint256 amount) external returns (bool)',
  'function allowance(address owner, address spender) external view returns (uint256)',
  'function transferFrom(address from, address to, uint256 amount) external returns (bool)',
  'function mint(address to, uint256 amount) external',
  'function burn(uint256 amount) external',
  'function currency() external view returns (string)',
  'function supplyCap() external view returns (uint256)',
  'function paused() external view returns (bool)',
  'function transferPolicyId() external view returns (uint64)',
  'function nonces(address owner) external view returns (uint256)',
  'function salts(address owner, bytes4 salt) external view returns (bool)',
  'function burnBlocked(address from, uint256 amount) external',
  'function mintWithMemo(address to, uint256 amount, bytes32 memo) external',
  'function burnWithMemo(uint256 amount, bytes32 memo) external',
  'function transferWithMemo(address to, uint256 amount, bytes32 memo) external',
  'function transferFromWithMemo(address from, address to, uint256 amount, bytes32 memo) external returns (bool)',
  'function changeTransferPolicyId(uint64 newPolicyId) external',
  'function setSupplyCap(uint256 newSupplyCap) external',
  'function pause() external',
  'function unpause() external',
  'function updateLinkingToken(address newLinkingToken) external',
  'function finalizeLinkingTokenUpdate() external',
  'function permit(address owner, address spender, uint256 value, uint256 deadline, uint8 v, bytes32 r, bytes32 s) external',
  'function DOMAIN_SEPARATOR() external view returns (bytes32)',
  'event Transfer(address indexed from, address indexed to, uint256 amount)',
  'event Approval(address indexed owner, address indexed spender, uint256 amount)',
  'event Mint(address indexed to, uint256 amount)',
  'event Burn(address indexed from, uint256 amount)',
  'event BurnBlocked(address indexed from, uint256 amount)',
  'event TransferWithMemo(address indexed from, address indexed to, uint256 amount, bytes32 memo)',
  'event TransferPolicyUpdate(address indexed updater, uint64 indexed newPolicyId)',
  'event SupplyCapUpdate(address indexed updater, uint256 indexed newSupplyCap)',
  'event PauseStateUpdate(address indexed updater, bool isPaused)',
  'event UpdateLinkingToken(address indexed updater, address indexed newLinkingToken)',
  'event LinkingTokenUpdateFinalized(address indexed updater, address indexed newLinkingToken)',
  'error InsufficientBalance()',
  'error InsufficientAllowance()',
  'error SupplyCapExceeded()',
  'error InvalidSignature()',
  'error InvalidPayload()',
  'error InvalidNonce()',
  'error StringTooLong()',
  'error PolicyForbids()',
  'error InvalidRecipient()',
  'error Expired()',
  'error SaltAlreadyUsed()',
  'error ContractPaused()',
  'error InvalidCurrency()',
  'error InvalidLinkingToken()',
  'error TransfersDisabled()',
  'function grantRole(bytes32 role, address account) external',
  'function revokeRole(bytes32 role, address account) external',
  'function renounceRole(bytes32 role) external',
  'function setRoleAdmin(bytes32 role, bytes32 adminRole) external',
  'function hasRole(address account, bytes32 role) external view returns (bool)',
  'function getRoleAdmin(bytes32 role) external view returns (bytes32)',
  'event RoleMembershipUpdated(bytes32 indexed role, address indexed account, address indexed sender, bool hasRole)',
  'event RoleAdminUpdated(bytes32 indexed role, bytes32 indexed newAdminRole, address indexed sender)',
  'error Unauthorized()',
])

export const tip20FactoryAbi = Abi.from([
  'function createToken( string memory name, string memory symbol, string memory currency, address linkingToken, address admin ) external returns (uint256)',
  'function tokenIdCounter() external view returns (uint256)',
  'event TokenCreated(address indexed token, uint256 indexed tokenId, string name, string symbol, string currency, address admin)',
])

export const tip403RegistryAbi = Abi.from([
  'function policyIdCounter() external view returns (uint64)',
  'function policyData(uint64 policyId) external view returns (uint8 policyType, address admin)',
  'function isAuthorized(uint64 policyId, address user) external view returns (bool)',
  'function createPolicy(address admin, uint8 policyType) external returns (uint64)',
  'function createPolicyWithAccounts(address admin, uint8 policyType, address[] accounts) external returns (uint64)',
  'function setPolicyAdmin(uint64 policyId, address admin) external',
  'function modifyPolicyWhitelist(uint64 policyId, address account, bool allowed) external',
  'function modifyPolicyBlacklist(uint64 policyId, address account, bool restricted) external',
  'event PolicyAdminUpdated(uint64 indexed policyId, address indexed updater, address indexed admin)',
  'event PolicyCreated(uint64 indexed policyId, address indexed updater, uint8 policyType)',
  'event WhitelistUpdated(uint64 indexed policyId, address indexed updater, address indexed account, bool allowed)',
  'event BlacklistUpdated(uint64 indexed policyId, address indexed updater, address indexed account, bool restricted)',
  'error Unauthorized()',
  'error IncompatiblePolicyType()',
  'error SelfOwnedPolicyMustBeWhitelist()',
])

export const tip4217RegistryAbi = Abi.from([
  'function getCurrencyDecimals(string currency) external view returns (uint8)',
])

export const tipAccountRegistrarAbi = Abi.from([
  'function delegateToDefault(bytes32 hash, bytes signature) external returns (address authority)',
  'function getDelegationMessage() external pure returns (string memory)',
  'error InvalidSignature()',
  'error CodeNotEmpty()',
  'error NonceNotZero()',
])

export const feeAmmAbi = Abi.from([
  'struct Pool { uint128 reserveUserToken; uint128 reserveValidatorToken; }',
  'struct PoolKey { address token0; address token1; }',
  'function getPoolId(address userToken, address validatorToken) external pure returns (bytes32)',
  'function getPool(address userToken, address validatorToken) external view returns (Pool memory)',
  'function pools(bytes32 poolId) external view returns (Pool memory)',
  'function mint(address userToken, address validatorToken, uint256 amountUserToken, uint256 amountValidatorToken, address to) returns (uint256 liquidity)',
  'function burn(address userToken, address validatorToken, uint256 liquidity, address to) returns (uint256 amountUserToken, uint256 amountValidatorToken)',
  'function totalSupply(bytes32 poolId) external view returns (uint256)',
  'function liquidityBalances(bytes32 poolId, address user) external view returns (uint256)',
  'function rebalanceSwap(address userToken, address validatorToken, uint256 amountOut, address to) external returns (uint256 amountIn)',
  'function calculateLiquidity(uint256 x, uint256 y) external pure returns (uint256)',
  'event Mint(address indexed sender, address indexed userToken, address indexed validatorToken, uint256 amountUserToken, uint256 amountValidatorToken, uint256 liquidity)',
  'event Burn(address indexed sender, address indexed userToken, address indexed validatorToken, uint256 amountUserToken, uint256 amountValidatorToken, uint256 liquidity, address to)',
  'event RebalanceSwap(address indexed userToken, address indexed validatorToken, address indexed swapper, uint256 amountIn, uint256 amountOut)',
  'event FeeSwap( address indexed userToken, address indexed validatorToken, uint256 amountIn, uint256 amountOut )',
  'error IdenticalAddresses()',
  'error ZeroAddress()',
  'error PoolExists()',
  'error PoolDoesNotExist()',
  'error InvalidToken()',
  'error InsufficientLiquidity()',
  'error OnlyProtocol()',
  'error InsufficientPoolBalance()',
  'error InsufficientReserves()',
  'error InsufficientLiquidityBalance()',
  'error MustDepositLowerBalanceToken()',
  'error InvalidAmount()',
  'error InvalidRebalanceState()',
  'error InvalidRebalanceDirection()',
  'error InvalidNewReserves()',
  'error CannotSupportPendingSwaps()',
  'error DivisionByZero()',
  'error InvalidSwapCalculation()',
  'error InsufficientLiquidityForPending()',
  'error TokenTransferFailed()',
  'error InternalError()',
])

export const feeManagerAbi = Abi.from([
  'struct FeeInfo { uint128 amount; bool hasBeenSet; }',
  'function BASIS_POINTS() external pure returns (uint256)',
  'function FEE_BPS() external pure returns (uint256)',
  'function userTokens(address user) external view returns (address)',
  'function validatorTokens(address validator) external view returns (address)',
  'function setUserToken(address token) external',
  'function setValidatorToken(address token) external',
  'function getFeeTokenBalance(address sender, address validator) external view returns (address, uint256)',
  'function executeBlock() external',
  'event UserTokenSet(address indexed user, address indexed token)',
  'event ValidatorTokenSet(address indexed validator, address indexed token)',
  'error OnlyValidator()',
  'error OnlySystemContract()',
  'error InvalidToken()',
  'error PoolDoesNotExist()',
  'error InsufficientLiquidity()',
  'error InsufficientFeeTokenBalance()',
  'error InternalError()',
  'error CannotChangeWithinBlock()',
  'error TokenPolicyForbids()',
])
