import { expect, test } from 'vitest'
import { createTempoClient } from './Client.js'

test('createTempoClient', () => {
  const client = createTempoClient()
  expect({ ...client, uid: null }).toMatchInlineSnapshot(`
    {
      "account": undefined,
      "amm": {
        "burn": [Function],
        "burnSync": [Function],
        "getLiquidityBalance": [Function],
        "getPool": [Function],
        "getPoolId": [Function],
        "getTotalSupply": [Function],
        "mint": [Function],
        "mintSync": [Function],
        "rebalanceSwap": [Function],
        "rebalanceSwapSync": [Function],
        "watchBurn": [Function],
        "watchFeeSwap": [Function],
        "watchMint": [Function],
        "watchRebalanceSwap": [Function],
      },
      "batch": undefined,
      "cacheTime": 500,
      "ccipRead": undefined,
      "chain": {
        "blockTime": 1000,
        "contracts": {
          "multicall3": {
            "address": "0xca11bde05977b3631167028862be2a173976ca11",
            "blockCreated": 0,
          },
        },
        "fees": undefined,
        "formatters": {
          "transaction": {
            "exclude": undefined,
            "format": [Function],
            "type": "transaction",
          },
          "transactionRequest": {
            "exclude": undefined,
            "format": [Function],
            "type": "transactionRequest",
          },
        },
        "id": 42427,
        "name": "Tempo Andante",
        "nativeCurrency": {
          "decimals": 6,
          "name": "USD",
          "symbol": "USD",
        },
        "rpcUrls": {
          "default": {
            "http": [
              "https://rpc-andante.tempoxyz.dev",
            ],
          },
        },
        "serializers": {
          "transaction": [Function],
        },
      },
      "dex": {
        "buy": [Function],
        "buySync": [Function],
        "cancel": [Function],
        "cancelSync": [Function],
        "createPair": [Function],
        "createPairSync": [Function],
        "getBalance": [Function],
        "getBuyQuote": [Function],
        "getOrder": [Function],
        "getPriceLevel": [Function],
        "getSellQuote": [Function],
        "place": [Function],
        "placeFlip": [Function],
        "placeFlipSync": [Function],
        "placeSync": [Function],
        "sell": [Function],
        "sellSync": [Function],
        "watchFlipOrderPlaced": [Function],
        "watchOrderCancelled": [Function],
        "watchOrderFilled": [Function],
        "watchOrderPlaced": [Function],
        "withdraw": [Function],
        "withdrawSync": [Function],
      },
      "extend": [Function],
      "fee": {
        "getUserToken": [Function],
        "setUserToken": [Function],
        "setUserTokenSync": [Function],
        "watchSetUserToken": [Function],
      },
      "key": "base",
      "name": "Base Client",
      "policy": {
        "create": [Function],
        "createSync": [Function],
        "getData": [Function],
        "isAuthorized": [Function],
        "modifyBlacklist": [Function],
        "modifyBlacklistSync": [Function],
        "modifyWhitelist": [Function],
        "modifyWhitelistSync": [Function],
        "setAdmin": [Function],
        "setAdminSync": [Function],
        "watchAdminUpdated": [Function],
        "watchBlacklistUpdated": [Function],
        "watchCreate": [Function],
        "watchWhitelistUpdated": [Function],
      },
      "pollingInterval": 500,
      "request": [Function],
      "token": {
        "approve": [Function],
        "approveSync": [Function],
        "burn": [Function],
        "burnBlocked": [Function],
        "burnBlockedSync": [Function],
        "burnSync": [Function],
        "changeTransferPolicy": [Function],
        "changeTransferPolicySync": [Function],
        "create": [Function],
        "createSync": [Function],
        "getAllowance": [Function],
        "getBalance": [Function],
        "getMetadata": [Function],
        "getRoleAdmin": [Function],
        "grantRoles": [Function],
        "grantRolesSync": [Function],
        "hasRole": [Function],
        "mint": [Function],
        "mintSync": [Function],
        "pause": [Function],
        "pauseSync": [Function],
        "permit": [Function],
        "permitSync": [Function],
        "renounceRoles": [Function],
        "renounceRolesSync": [Function],
        "revokeRoles": [Function],
        "revokeRolesSync": [Function],
        "setRoleAdmin": [Function],
        "setRoleAdminSync": [Function],
        "setSupplyCap": [Function],
        "setSupplyCapSync": [Function],
        "transfer": [Function],
        "transferSync": [Function],
        "unpause": [Function],
        "unpauseSync": [Function],
        "watchAdminRole": [Function],
        "watchApprove": [Function],
        "watchBurn": [Function],
        "watchCreate": [Function],
        "watchMint": [Function],
        "watchRole": [Function],
        "watchTransfer": [Function],
      },
      "transport": {
        "fetchOptions": undefined,
        "key": "http",
        "methods": undefined,
        "name": "HTTP JSON-RPC",
        "request": [Function],
        "retryCount": 3,
        "retryDelay": 150,
        "timeout": 10000,
        "type": "http",
        "url": "https://rpc-andante.tempoxyz.dev",
      },
      "type": "base",
      "uid": null,
    }
  `)
})
