name: Verify
on:
  workflow_call:
    secrets:
      VITE_RPC_CREDENTIALS:
        required: false
  workflow_dispatch:

permissions:
  contents: read

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Check code
        run: pnpm check

      - name: Check types
        run: pnpm run check:types

      - name: Check build
        run: pnpm build

  test-localnet:
    name: 'Test Runtime (env: localnet, tag: ${{ matrix.tag }})'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        tag: 
          - https://rpc.moderato.tempo.xyz

    steps:
      - name: Clone repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Setup Docker
        uses: docker/setup-docker-action@1a6edb0ba9ac496f6850236981f15d8f9a82254d # v5.0.0

      - name: Run tests
        run: pnpm test --bail=1
        env:
          CI: true
          VITE_NODE_TAG: ${{ matrix.tag }}
          VITE_RPC_CREDENTIALS: ${{ secrets.VITE_RPC_CREDENTIALS }}
